---
- hosts: all
  sudo: true
  tasks: 
  - name: Install epel-release
    yum: name=epel-release state=latest
  - name: Install dependencies
    yum: pkg={{item}} state=latest
    with_items:
    - git
    - patch
    - wget
  - name: Download python pip installer
    command: wget -c https://bootstrap.pypa.io/get-pip.py
    args:
      chdir: /root
  - name: Run python pip installer
    command: python get-pip.py
    args:
      chdir: /root
  - name: Install os-testr
    pip: name=os-testr state=latest
  - name: Download six
    command: "{{item}}"
    with_items: 
    - wget -c https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz#md5=34eed507548117b2ab523ab14b2f8b55
    - tar -xf six-1.10.0.tar.gz 
    args: 
      chdir: /root
  - name: Install six
    command: python setup.py install
    args: 
      chdir: /root/six-1.10.0
  - name: Include liberty-odl playbook
    include: liberty-odl-kuryr/playbook.yml
